version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${METHOD}
    command: postgres -N 512
    volumes:
       - db:/data/postgres
    expose:
      - ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - djangonetwork
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        "max-size": "1m"
        "max-file": "5"

networks:
  djangonetwork:
    driver: bridge

volumes:
    db: