"""События домена DogCity."""

from src.domain.events.account_moderation import (
    AccountBlocked,
    AccountDeleted,
    AccountModerationEvent,
    AccountUnblocked,
    AccountVerified,
    DocumentsSubmitted,
    ModerationOpened,
    VerificationRejected,
)
from src.domain.events.base import DomainEvent
from src.domain.events.order import (
    OrderCancelled,
    OrderCompleted,
    OrderConfirmed,
    OrderEvent,
    OrderPlaced,
    OrderRejected,
    OrderStarted,
)
from src.domain.events.owner import (
    OwnerAddressChanged,
    OwnerContactsChanged,
    OwnerEvent,
    OwnerRegistered,
    OwnerReviewReceived,
    PetAdded,
    PetBehaviorUpdated,
    PetRemoved,
    PetWeightUpdated,
    VaccinationAdded,
)
from src.domain.events.review import ReviewEvent, ReviewPublished
from src.domain.events.sitter import (
    AcceptedDogSizesChanged,
    CapacityChanged,
    OfferPublished,
    OfferWithdrawn,
    SitterAddressChanged,
    SitterContactsChanged,
    SitterEvent,
    SitterRegistered,
    SitterReviewReceived,
)
from src.domain.events.sitter_schedule import (
    BookingReleased,
    BookingReserved,
    SitterScheduleEvent,
)

__all__ = (
    "AcceptedDogSizesChanged",
    "AccountBlocked",
    "AccountDeleted",
    "AccountModerationEvent",
    "AccountUnblocked",
    "AccountVerified",
    "BookingReleased",
    "BookingReserved",
    "CapacityChanged",
    "DocumentsSubmitted",
    "DomainEvent",
    "ModerationOpened",
    "OfferPublished",
    "OfferWithdrawn",
    "OrderCancelled",
    "OrderCompleted",
    "OrderConfirmed",
    "OrderEvent",
    "OrderPlaced",
    "OrderRejected",
    "OrderStarted",
    "OwnerAddressChanged",
    "OwnerContactsChanged",
    "OwnerEvent",
    "OwnerRegistered",
    "OwnerReviewReceived",
    "PetAdded",
    "PetBehaviorUpdated",
    "PetRemoved",
    "PetWeightUpdated",
    "ReviewEvent",
    "ReviewPublished",
    "SitterAddressChanged",
    "SitterContactsChanged",
    "SitterEvent",
    "SitterRegistered",
    "SitterReviewReceived",
    "SitterScheduleEvent",
    "VaccinationAdded",
    "VerificationRejected",
)
